// Generated by gencpp from file xu_runtime_monitoring/AverageSpeedResponse.msg
// DO NOT EDIT!


#ifndef XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDRESPONSE_H
#define XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xu_runtime_monitoring
{
template <class ContainerAllocator>
struct AverageSpeedResponse_
{
  typedef AverageSpeedResponse_<ContainerAllocator> Type;

  AverageSpeedResponse_()
    : ave_speed(0.0)  {
    }
  AverageSpeedResponse_(const ContainerAllocator& _alloc)
    : ave_speed(0.0)  {
  (void)_alloc;
    }



   typedef double _ave_speed_type;
  _ave_speed_type ave_speed;





  typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AverageSpeedResponse_

typedef ::xu_runtime_monitoring::AverageSpeedResponse_<std::allocator<void> > AverageSpeedResponse;

typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedResponse > AverageSpeedResponsePtr;
typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedResponse const> AverageSpeedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xu_runtime_monitoring

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xu_runtime_monitoring': ['/home/stark/catkin_ws/src/xu_runtime_monitoring/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "920d4e4fb7f153b9c0a8d2270418ac0e";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x920d4e4fb7f153b9ULL;
  static const uint64_t static_value2 = 0xc0a8d2270418ac0eULL;
};

template<class ContainerAllocator>
struct DataType< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xu_runtime_monitoring/AverageSpeedResponse";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ave_speed\n\
\n\
";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ave_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AverageSpeedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xu_runtime_monitoring::AverageSpeedResponse_<ContainerAllocator>& v)
  {
    s << indent << "ave_speed: ";
    Printer<double>::stream(s, indent + "  ", v.ave_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDRESPONSE_H
