// Generated by gencpp from file xu_runtime_monitoring/AverageSpeedRequest.msg
// DO NOT EDIT!


#ifndef XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDREQUEST_H
#define XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xu_runtime_monitoring
{
template <class ContainerAllocator>
struct AverageSpeedRequest_
{
  typedef AverageSpeedRequest_<ContainerAllocator> Type;

  AverageSpeedRequest_()
    : distance(0.0)
    , time(0.0)  {
    }
  AverageSpeedRequest_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AverageSpeedRequest_

typedef ::xu_runtime_monitoring::AverageSpeedRequest_<std::allocator<void> > AverageSpeedRequest;

typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedRequest > AverageSpeedRequestPtr;
typedef boost::shared_ptr< ::xu_runtime_monitoring::AverageSpeedRequest const> AverageSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xu_runtime_monitoring

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xu_runtime_monitoring': ['/home/stark/catkin_ws/src/xu_runtime_monitoring/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbac7e718df1ff81065bd08fbabb1c57";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbac7e718df1ff81ULL;
  static const uint64_t static_value2 = 0x065bd08fbabb1c57ULL;
};

template<class ContainerAllocator>
struct DataType< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xu_runtime_monitoring/AverageSpeedRequest";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
float64 time\n\
";
  }

  static const char* value(const ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AverageSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xu_runtime_monitoring::AverageSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XU_RUNTIME_MONITORING_MESSAGE_AVERAGESPEEDREQUEST_H
