min_distance: 0.1
max_distance: 100.0
min_angle: -45.0
max_angle: 225.0
angle_increment: 0.00436515314505
theta: 30 # look closer
lookahead_distance: 1
desired_distance: 1
followXXX: "right"

kp: 2
kd: 0.1
min_speed: 0.5
mid_speed: 1
max_speed: 1.5
min_steer_angle: 10
max_steer_angle: 20
